import { IExerciseEquipment, IExerciseMuscle } from "../types/workout";

export const EXERCISE_CATEGORIES: IExerciseMuscle[] = [
  "chest",
  "upper_back",
  "lats",
  "shoulders_front",
  "shoulders_side",
  "shoulders_rear",
  "biceps",
  "triceps",
  "forearms",
  "abs",
  "obliques",
  "lower_back",
  "glutes",
  "quads",
  "hamstrings",
  "calves",
  "hip_flexors",
  "full_body",
];

export const EXERCISE_CATEGORY_LABELS: Record<IExerciseMuscle, string> = {
  chest: "Pecho",
  upper_back: "Espalda alta",
  lats: "Dorsales",
  shoulders_front: "Hombro frontal",
  shoulders_side: "Hombro lateral",
  shoulders_rear: "Hombro posterior",
  biceps: "Bíceps",
  triceps: "Tríceps",
  forearms: "Antebrazos",
  abs: "Abdominales",
  obliques: "Oblicuos",
  lower_back: "Zona lumbar",
  glutes: "Glúteos",
  quads: "Cuádriceps",
  hamstrings: "Isquiotibiales",
  calves: "Gemelos",
  hip_flexors: "Flexores de cadera",
  full_body: "Cuerpo completo",
};

export const EXERCISE_EQUIPMENT_LABELS: Record<IExerciseEquipment, string> = {
  bodyweight: "Peso corporal",
  barbell: "Barra",
  dumbbell: "Mancuerna",
  kettlebell: "Kettlebell",
  ez_bar: "Barra EZ",
  plate: "Disco",
  cable: "Cable",
  machine: "Máquina",
  smith_machine: "Máquina Smith",
  bench: "Banco",
  pull_up_bar: "Barra de dominadas",
  dip_bars: "Barras de fondos",
  resistance_band: "Banda elástica",
  trap_bar: "Barra trampa",
  landmine: "Landmine",
  suspension_trainer: "TRX",
  medicine_ball: "Balón medicinal",
  cardio_machine: "Máquina cardio",
};
