import { IExerciseEquipment, IExerciseMuscle } from "../types/workout";

export const EXERCISE_CATEGORIES: IExerciseMuscle[] = [
  "chest_upper",
  "chest_middle",
  "chest_lower",
  "front_delts",
  "side_delts",
  "rear_delts",
  "triceps",
  "lats",
  "rhomboids",
  "mid_traps",
  "lower_traps",
  "upper_traps",
  "biceps",
  "forearms",
  "rectus_abdominis",
  "obliques",
  "transverse_abdominis",
  "erector_spinae",
  "lower_back",
  "quads",
  "hamstrings",
  "glutes",
  "calves",
  "hip_flexors",
  "hip_adductors",
  "hip_abductors",
  "serratus_anterior",
  "rotator_cuff",
  "full_body",
];

export const EXERCISE_CATEGORY_LABELS: Record<IExerciseMuscle, string> = {
  chest_upper: "Pecho superior",
  chest_middle: "Pecho medio",
  chest_lower: "Pecho inferior",
  front_delts: "Deltoides frontales",
  side_delts: "Deltoides laterales",
  rear_delts: "Deltoides posteriores",
  triceps: "Tríceps",
  lats: "Dorsales",
  rhomboids: "Romboides",
  mid_traps: "Trapecio medio",
  lower_traps: "Trapecio inferior",
  upper_traps: "Trapecio superior",
  biceps: "Bíceps",
  forearms: "Antebrazos",
  rectus_abdominis: "Recto abdominal",
  obliques: "Oblicuos",
  transverse_abdominis: "Transverso abdominal",
  erector_spinae: "Erectores espinales",
  lower_back: "Zona lumbar",
  quads: "Cuádriceps",
  hamstrings: "Isquiotibiales",
  glutes: "Glúteos",
  calves: "Gemelos",
  hip_flexors: "Flexores de cadera",
  hip_adductors: "Aductores de cadera",
  serratus_anterior: "Serrato anterior",
  rotator_cuff: "Manguito rotador",
  full_body: "Cuerpo completo",
  hip_abductors: "Abductores de cadera",
};

export const EXERCISE_EQUIPMENT_LABELS: Record<IExerciseEquipment, string> = {
  barbell: "Barra",
  ez_curl_bar: "Barra EZ",
  dumbbell: "Mancuerna",
  kettlebell: "Kettlebell",
  weight_plate: "Disco de peso",
  cable_machine: "Máquina de cable",
  smith_machine: "Máquina Smith",
  leg_press: "Prensa de piernas",
  lat_pulldown: "Jalón de dorsales",
  chest_press_machine: "Máquina de press de pecho",
  leg_curl_machine: "Máquina de curl de piernas",
  leg_extension_machine: "Máquina de extensión de piernas",
  seated_row_machine: "Máquina de remo sentado",
  shoulder_press_machine: "Máquina de press de hombros",
  bodyweight: "Peso corporal",
  pull_up_bar: "Barra de dominadas",
  dip_station: "Estación de fondos",
  parallel_bars: "Barras paralelas",
  resistance_band: "Bandas de resistencia",
  suspension_trainer: "Entrenador de suspensión",
  medicine_ball: "Balón medicinal",
  stability_ball: "Balón de estabilidad",
  foam_roller: "Rodillo de espuma",
  ab_wheel: "Rueda de abdominales",
  flat_bench: "Banco plano",
  incline_bench: "Banco inclinado",
  decline_bench: "Banco declinado",
  preacher_bench: "Banco predicador",
};
