import type { MeasurementTemplateId } from "@/shared/types/measurement";
import {
  ProgramTemplate,
  RoutineTemplate,
  RoutineTemplateData,
} from "../../types";

export const FULL_BODY_BEGINNER_PROGRAM: ProgramTemplate = {
  id: "full-body-beginner-program",
  name: "Full Body - Principiante (Hipertrofia)",
  description:
    "Programa full-body de 3 días/semana orientado a hipertrofia para principiantes. Enfoque en movimientos compuestos básicos, técnica y progresión gradual. Duración recomendada 8 semanas con aumento de peso o repeticiones semana a semana.",
  category: "hypertrophy",
  difficulty: "beginner",
  duration: "8 semanas",
  frequency: "3x semana",
  equipment: [
    "barbell",
    "dumbbell",
    "cable",
    "machine",
    "pull_up_bar",
    "resistance_band",
    "bench",
    "smith_machine",
  ],
  routines: [
    {
      routineId: "fullbody-day-a",
      assignedDays: ["monday"],
      name: "Full Body A",
    },
    {
      routineId: "fullbody-day-b",
      assignedDays: ["wednesday"],
      name: "Full Body B",
    },
    {
      routineId: "fullbody-day-c",
      assignedDays: ["friday"],
      name: "Full Body C",
    },
  ],
};

export const FULL_BODY_BEGINNER_ROUTINES: RoutineTemplate[] = [
  {
    id: "fullbody-day-a",
    name: "Full Body A",
    description:
      "Día A: énfasis en sentadilla, press horizontal y remo. Técnica y control para principiantes.",
    category: "hypertrophy",
    difficulty: "beginner",
    estimatedTime: "45-60 min",
    targetMuscles: [
      "quads",
      "chest",
      "lats",
      "shoulders_front",
      "biceps",
      "abs",
    ],
    tags: ["full-body", "beginner", "hypertrophy"],
    equipment: ["barbell", "dumbbell", "bench", "cable", "pull_up_bar"],
    weeklyFrequency: 1,
  },
  {
    id: "fullbody-day-b",
    name: "Full Body B",
    description:
      "Día B: variante de piernas con prensa, press inclinado y jalón. Complementos de hombro y core.",
    category: "hypertrophy",
    difficulty: "beginner",
    estimatedTime: "45-60 min",
    targetMuscles: ["quads", "chest", "lats", "triceps", "abs"],
    tags: ["full-body", "beginner", "hypertrophy"],
    equipment: ["machine", "dumbbell", "bench", "cable", "resistance_band"],
    weeklyFrequency: 1,
  },
  {
    id: "fullbody-day-c",
    name: "Full Body C",
    description:
      "Día C: peso muerto convencional como lift principal, press vertical y remo con mancuernas. Trabajo de brazos y lateral core.",
    category: "hypertrophy",
    difficulty: "beginner",
    estimatedTime: "45-60 min",
    targetMuscles: [
      "hamstrings",
      "glutes",
      "shoulders_front",
      "lats",
      "biceps",
      "abs",
    ],
    tags: ["full-body", "beginner", "hypertrophy"],
    equipment: ["barbell", "dumbbell", "bench", "machine", "cable"],
    weeklyFrequency: 1,
  },
];

export const FULL_BODY_BEGINNER_DATA: Record<string, RoutineTemplateData> = {
  "fullbody-day-a": {
    id: "fullbody-day-a",
    routine: {
      name: "Full Body A",
      folder_id: null,
      training_days: null,
      show_rpe: false,
      show_tempo: false,
    },
    blocks: [
      {
        type: "individual",
        name: "Sentadilla con barra",
        order_index: 0,
        rest_time_seconds: 90,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Press de banca con barra",
        order_index: 1,
        rest_time_seconds: 90,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Remo con barra",
        order_index: 2,
        rest_time_seconds: 90,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Press militar con mancuernas",
        order_index: 3,
        rest_time_seconds: 90,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Curl de bíceps con mancuernas",
        order_index: 4,
        rest_time_seconds: 60,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Crunch abdominal clásico",
        order_index: 5,
        rest_time_seconds: 60,
        rest_between_exercises_seconds: 0,
      },
    ],
    exercisesInBlock: [
      {
        block_index: 0,
        exercise_id: "uuid-sentadilla-barra-001",
        exercise_name: "Sentadilla con barra",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 1,
        exercise_id: "uuid-press-banca-barra",
        exercise_name: "Press de banca con barra",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 2,
        exercise_id: "uuid-bentoverrow-barbell-004",
        exercise_name: "Remo con barra",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 3,
        exercise_id: "uuid-press-militar-mancuernas-002",
        exercise_name: "Press militar con mancuernas",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 4,
        exercise_id: "Curl de bíceps con mancuernas",
        exercise_name: "Curl de bíceps con mancuernas",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 5,
        exercise_id: "uuid-curl-mancuernas-002",
        exercise_name: "Crunch abdominal clásico",
        order_index: 0,
        notes: null,
      },
    ],
    sets: [
      // Sentadilla con barra (compuesto) 3x8-10 (usamos 8 reps fijas para beginner)
      {
        exercise_block_index: 0,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 0,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 0,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Press de banca con barra 3x8-10
      {
        exercise_block_index: 1,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 1,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 1,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Remo con barra 3x8-10
      {
        exercise_block_index: 2,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 2,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 2,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Press militar con mancuernas 3x8-10
      {
        exercise_block_index: 3,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 3,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 3,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Curl de bíceps con mancuernas 3x10-12
      {
        exercise_block_index: 4,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 10,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 4,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 10,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 4,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 10,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Crunch abdominal clásico 3x15
      {
        exercise_block_index: 5,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 15,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 5,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 15,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 5,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 15,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
    ],
  },

  "fullbody-day-b": {
    id: "fullbody-day-b",
    routine: {
      name: "Full Body B",
      folder_id: null,
      training_days: null,
      show_rpe: false,
      show_tempo: false,
    },
    blocks: [
      {
        type: "individual",
        name: "Prensa de piernas",
        order_index: 0,
        rest_time_seconds: 90,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Press inclinado con mancuernas",
        order_index: 1,
        rest_time_seconds: 90,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Jalón al pecho en polea",
        order_index: 2,
        rest_time_seconds: 90,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Elevaciones laterales con mancuernas",
        order_index: 3,
        rest_time_seconds: 60,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Extensión de tríceps con cuerda en polea alta",
        order_index: 4,
        rest_time_seconds: 60,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Plancha frontal",
        order_index: 5,
        rest_time_seconds: 60,
        rest_between_exercises_seconds: 0,
      },
    ],
    exercisesInBlock: [
      {
        block_index: 0,
        exercise_id: "uuid-prensa-piernas-005",
        exercise_name: "Prensa de piernas",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 1,
        exercise_id: "uuid-press-inclinado-mancuernas",
        exercise_name: "Press inclinado con mancuernas",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 2,
        exercise_id: "uuid-latpulldown-002",
        exercise_name: "Jalón al pecho en polea",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 3,
        exercise_id: "uuid-elevaciones-laterales-mancuernas-004",
        exercise_name: "Elevaciones laterales con mancuernas",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 4,
        exercise_id: "uuid-triceps-ropepushdown-006",
        exercise_name: "Extensión de tríceps con cuerda en polea alta",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 5,
        exercise_id: "uuid-plancha-frontal-005",
        exercise_name: "Plancha frontal",
        order_index: 0,
        notes: null,
      },
    ],
    sets: [
      // Prensa de piernas 3x8
      {
        exercise_block_index: 0,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 0,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 0,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Press inclinado con mancuernas 3x8
      {
        exercise_block_index: 1,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 1,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 1,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Jalón al pecho en polea 3x10
      {
        exercise_block_index: 2,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 10,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 2,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 10,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 2,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 10,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Elevaciones laterales con mancuernas 3x12
      {
        exercise_block_index: 3,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 12,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 3,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 12,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 3,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 12,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Extensión de tríceps con cuerda en polea alta 3x12
      {
        exercise_block_index: 4,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 12,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 4,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 12,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 4,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 12,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Plancha frontal 3x30 (segundos) - usamos reps como segundos y reps_type "time"
      {
        exercise_block_index: 5,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 30,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "time_only" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 5,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 30,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "time_only" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 5,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 30,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "time_only" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
    ],
  },

  "fullbody-day-c": {
    id: "fullbody-day-c",
    routine: {
      name: "Full Body C",
      folder_id: null,
      training_days: null,
      show_rpe: false,
      show_tempo: false,
    },
    blocks: [
      {
        type: "individual",
        name: "Peso muerto convencional",
        order_index: 0,
        rest_time_seconds: 90,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Press de banca con mancuernas",
        order_index: 1,
        rest_time_seconds: 90,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Remo con mancuernas",
        order_index: 2,
        rest_time_seconds: 90,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Elevaciones laterales con mancuernas",
        order_index: 3,
        rest_time_seconds: 60,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Curl de bíceps con barra",
        order_index: 4,
        rest_time_seconds: 60,
        rest_between_exercises_seconds: 0,
      },
      {
        type: "individual",
        name: "Plancha lateral",
        order_index: 5,
        rest_time_seconds: 60,
        rest_between_exercises_seconds: 0,
      },
    ],
    exercisesInBlock: [
      {
        block_index: 0,
        exercise_id: "uuid-deadlift-008",
        exercise_name: "Peso muerto convencional",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 1,
        exercise_id: "uuid-press-banca-mancuernas",
        exercise_name: "Press de banca con mancuernas",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 2,
        exercise_id: "uuid-onearmrow-db-005",
        exercise_name: "Remo con mancuernas",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 3,
        exercise_id: "uuid-elevaciones-laterales-mancuernas-004",
        exercise_name: "Elevaciones laterales con mancuernas",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 4,
        exercise_id: "uuid-curl-barra-001",
        exercise_name: "Curl de bíceps con barra",
        order_index: 0,
        notes: null,
      },
      {
        block_index: 5,
        exercise_id: "uuid-plancha-lateral-006",
        exercise_name: "Plancha lateral",
        order_index: 0,
        notes: null,
      },
    ],
    sets: [
      // Peso muerto convencional 3x8
      {
        exercise_block_index: 0,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 0,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 0,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Press de banca con mancuernas 3x8
      {
        exercise_block_index: 1,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 1,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 1,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Remo con mancuernas 3x8-10
      {
        exercise_block_index: 2,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 2,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 2,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 8,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Elevaciones laterales con mancuernas 3x12
      {
        exercise_block_index: 3,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 12,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 3,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 12,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 3,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 12,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Curl de bíceps con barra 3x10
      {
        exercise_block_index: 4,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 10,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 4,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 10,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 4,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 10,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "weight_reps" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },

      // Plancha lateral 3x20s (usamos reps=20 y reps_type="time")
      {
        exercise_block_index: 5,
        exercise_order_index: 0,
        order_index: 0,
        secondary_value: 20,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "time_only" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 5,
        exercise_order_index: 0,
        order_index: 1,
        secondary_value: 20,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "time_only" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
      {
        exercise_block_index: 5,
        exercise_order_index: 0,
        order_index: 2,
        secondary_value: 20,

        primary_value: null,
        rpe: null,
        tempo: null,
        set_type: "normal",
        measurement_template: "time_only" as MeasurementTemplateId,
        primary_range: null,
        secondary_range: null,
      },
    ],
  },
};
