export type MutationCode =
  | "ROUTINE_CREATE"
  | "ROUTINE_UPDATE"
  | "ROUTINE_DELETE"
  | "ROUTINE_CLEAR_TRAINING_DAYS"
  | "ROUTINE_CREATE_QUICK_WORKOUT"
  | "ROUTINE_CONVERT_FROM_QUICK"
  | "ROUTINE_UPDATE_FOLDER"
  | "FOLDER_CREATE"
  | "FOLDER_UPDATE"
  | "FOLDER_DELETE"
  | "FOLDER_REORDER"
  // Tracker Entries
  | "TRACKER_ENTRY_CREATE"
  | "TRACKER_ENTRY_UPDATE"
  | "TRACKER_ENTRY_DELETE"
  | "TRACKER_ENTRY_FROM_QUICK_ACTION"
  // Tracker Metrics
  | "TRACKER_METRIC_CREATE"
  | "TRACKER_METRIC_UPDATE"
  | "TRACKER_METRIC_DELETE"
  | "TRACKER_METRIC_RESTORE"
  | "TRACKER_METRIC_REORDER"
  | "TRACKER_METRIC_FROM_TEMPLATE"
  // Tracker Quick Actions
  | "TRACKER_QUICK_ACTION_CREATE"
  | "TRACKER_QUICK_ACTION_DELETE"
  // Tracker Atomic Operations
  | "TRACKER_ENTRY_WITH_AGGREGATE"
  | "TRACKER_REPLACE_ENTRY_WITH_AGGREGATE"
  | "TRACKER_DELETE_ENTRY_WITH_AGGREGATE"
  // Macro Targets
  | "MACRO_TARGET_UPSERT"
  | "MACRO_TARGET_UPDATE"
  // Macro Entries
  | "MACRO_ENTRY_CREATE"
  | "MACRO_ENTRY_UPDATE"
  | "MACRO_ENTRY_DELETE"
  // Macro Quick Actions
  | "MACRO_QUICK_ACTIONS_INIT"
  | "MACRO_QUICK_ACTION_CREATE"
  | "MACRO_QUICK_ACTION_DELETE"
  // PR
  | "PR_UPDATE"
  | "PR_CREATE"
  | "WORKOUT_START"
  | "WORKOUT_COMPLETE"
  | "WORKOUT_UPDATE"
  | "FINISH_WORKOUT"
  | "USER_PREFERENCES_CREATE"
  | "USER_PREFERENCES_UPDATE";
